services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network

  apache:
    image: httpd
    container_name: apache-server
    networks:
      - my-network

networks:
  my-network:
